services:
  api:
    build: .
    environment:
      GALILEO_HR_MANAGER_POSTGRES_HOST: ${GALILEO_HR_MANAGER_POSTGRES_HOST}
      GALILEO_HR_MANAGER_POSTGRES_USER: ${GALILEO_HR_MANAGER_POSTGRES_USER}
      GALILEO_HR_MANAGER_POSTGRES_PASSWORD: ${GALILEO_HR_MANAGER_POSTGRES_PASSWORD}
      GALILEO_HR_MANAGER_POSTGRES_DB: ${GALILEO_HR_MANAGER_POSTGRES_DB}
      GALILEO_HR_MANAGER_POSTGRES_PORT: ${GALILEO_HR_MANAGER_POSTGRES_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
