postgre_sql:
  host: ${GALILEO_HR_MANAGER_POSTGRES_HOST}
  user: ${GALILEO_HR_MANAGER_POSTGRES_USER}
  password: ${GALILEO_HR_MANAGER_POSTGRES_PASSWORD}
  database: ${GALILEO_HR_MANAGER_POSTGRES_DB}
  port: ${GALILEO_HR_MANAGER_POSTGRES_PORT}
